---
name: Tox
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  # Run the tox tests every 8 hours.
  # This will help to identify faster if
  # there is a CI failure related to a
  # change in any dependency.
  schedule:
    - cron: '0 */8 * * *'
  # Run on demand
  workflow_dispatch:
jobs:
  tox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: python -m pip install tox

      - name: Run tox
        run: |
          python -m tox
